### PR TITLE
added doc about Gatsby support

### PR DESCRIPTION
**Pull request by logan-anderson**
Added a small doc in the guides section (Not sure if this is the best spot for it but it made the most sense to me).  That points the users to information about how to use TinaCMS and Gatsby

### CODE REVIEW

**Comment by jamespohalloran** [comment]
There's a few Next Docs deleted in this. They seem still relevant, and the sidebar still links to them and 404's.

**Review by jamespohalloran — CHANGES_REQUESTED** [review]
https://github.com/tinacms/tina.io/pull/1463#issuecomment-1375906824

**Comment by logan-anderson** [comment]
> There's a few Next Docs deleted in this. They seem still relevant, and the sidebar still links to them and 404's.

Hmm I am not sure what happened there. I did not mean to delete them. I will undo it.

**Comment by logan-anderson** [comment]
I updated it now. Thanks @jamespohalloran

**Review by jamespohalloran — APPROVED** [review]
Nice!

**Pull request merged**
