### PR TITLE
Tina/content ai blog post

### PR DESCRIPTION
**Pull request by logan-anderson**

### CODE REVIEW

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Review by jamespohalloran — CHANGES_REQUESTED** [review]

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

**Comment by logan-anderson** [comment]
test

**Comment by logan-anderson** [comment]
test

**Comment by logan-anderson** [comment]
test

**Comment by logan-anderson** [comment]
test

**Comment by logan-anderson** [comment]
test

**Comment by logan-anderson** [comment]
test

**Comment by logan-anderson** [comment]
test

**Comment by logan-anderson** [comment]
test

**Comment by logan-anderson** [comment]
test

**Comment by logan-anderson** [comment]
ai fix: content/blog/Supercharge-Your-Markdown-Blog-with-AI.md

prompt: only return a single suggestion

**Comment by logan-anderson** [comment]
@jamespohalloran This PR is getting a bit large with all of the comments I have done for testing. Going to close this and open a new one.

**Pull request closed without merging**
