### PR TITLE
♻️ Refactor Icon Selector Component

### PR DESCRIPTION
**Pull request by joshbermanssw**
As per https://github.com/tinacms/tina.io/issues/2086 i have refactored the icon selector component to have

 1. a drop down,
 2. displaying the icons nexto the names and 
 3. removing the prefix (i.e 'Fa') 
 
Screenshot 2024-09-02 at 5 59 17 PM

**Figure: Click 'Show Icons'**

Screenshot 2024-09-02 at 5 59 37 PM

**Figure: New Icon Selector**

### CODE REVIEW

**Comment by bradystroud** [comment]
Can you add some padding around the icons

**Comment by joshbermanssw** [comment]
Screenshot 2024-09-02 at 9 15 20 PM

**Figure: Added padding to the icons**

**Review by bradystroud — APPROVED** [review]
LGTM

**Comment by bradystroud** [comment]
I made it look prettier

image

**Review by isaaclombardssw — APPROVED** [review]
Really smooth UI. Should there be a way to deselect icons (i.e. none selected)?

If we don't want thatm it's great.

**Comment by bradystroud** [comment]
> Really smooth UI. Should there be a way to deselect icons (i.e. none selected)?
> 
> If we don't want that, it's great.

moved this to a PBI
#2138

**Pull request merged**
