### PR TITLE
increase logos >1024px

### PR DESCRIPTION
**Pull request by joshbermanssw**
As per https://github.com/tinacms/tina.io/issues/1927 we have increased the number of logos shown on the screen for > 1024px to 6 (from 5)

### CODE REVIEW

**Comment by bettybondoc** [comment]
✅ Test pass - preview looks good

**Review by bradystroud — APPROVED** [review]

**Review by bradystroud — CHANGES_REQUESTED** [review]
This change is not very responsive

**Review by bradystroud — APPROVED** [review]
LGTM

**Comment by bettybondoc** [comment]
✅ Mobile view looks good!

**Pull request merged**
