### PR TITLE
🌍 Events Component - Functionality Reworks

### PR DESCRIPTION
**Pull request by joshbermanssw**
We reviewed the events component from the perspective of tablet and mobile users and saw some slight issues with it. 

Screenshot 2024-08-28 at 3 09 53 AM

**Figure: Current 🌍 Component**

Screenshot 2024-08-28 at 4 19 28 AM

**Figure: 🌍 Component (gray)**

Changes in this PR: 
- [ ] Reduce movement speed of globe to 1/5 original speed 
- [ ] Moved the <Link> to just the 'Read More' text so that tablet users can interact with the cards and globe
- [ ] Added UI to show whether an event has occurred or not

### CODE REVIEW

**Review by isaaclombardssw — APPROVED** [review]
Looks great.

**Comment by joshbermanssw** [comment]
Update - new design https://www.figma.com/design/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=1235-4638&t=Bsi8jvNLLrqp4Ans-0

**Comment by joshbermanssw** [comment]
Screenshot 2024-08-29 at 5 37 22 AM

Updated UI based off of figma

**Comment by bettybondoc** [comment]
> Screenshot 2024-08-29 at 5 37 22 AM
> Updated UI based off of figma

@joshbermanssw 

- [ ] 1 - Pill - Please change border-radius from rounded-lg to rounded
- [ ] 1 - Pill - Please make the font size text-sm
- [ ] 1 - Ongoing/Future Events - Please add transparency 60 to pill background
- [ ] 1 - Past Events - Please change pill background to slate-200 and add transparency 60
- [ ] 2 - Fix icon alignment with "Read more"
- [ ] 3 - Please reduce padding so it's consistent with other sides

image

**Comment by joshbermanssw** [comment]
Screenshot 2024-08-29 at 4 54 23 PM

Updated after UI changes

**Comment by joshbermanssw** [comment]
test passed by @bettybondoc

**Pull request merged**
