### PR TITLE
added defaultItem docs

### PR DESCRIPTION
**Pull request by logan-anderson**
fixes ENG-598
fixes https://linear.app/tina/issue/ENG-598/list-true-not-fully-documented-in-reference-docs

### CODE REVIEW

**Comment by jamespohalloran** [comment]
Does `defaultItem` & `list: true` need to be added to other field types? I assumed that you could have a list of numbers for instance, but maybe that's not supported?

**Comment by logan-anderson** [comment]
> Does `defaultItem` & `list: true` need to be added to other field types? I assumed that you could have a list of numbers for instance, but maybe that's not supported?

I think it is supported in the backend but not by our UI

**Comment by jeffsee55** [comment]
>  I assumed that you could have a list of numbers for instance, but maybe that's not supported?

You can but the list of items you can do with that is incomplete I believe, I think `string`, `number`, maybe `boolean`, but then not `rich-text` or `image`

**Comment by jamespohalloran** [comment]
> > I assumed that you could have a list of numbers for instance, but maybe that's not supported?
> 
> You can but the list of items you can do with that is incomplete I believe, I think `string`, `number`, maybe `boolean`, but then not `rich-text` or `image`

I just checked, it does look like it's only supported through the UI on strings & objects, so the docs are correct.

**Review by jamespohalloran — APPROVED** [review]

**Pull request merged**
