### PR TITLE
💄 Mobile Experience Homepage Upgrade

### PR DESCRIPTION
**Pull request by isaaclombardssw**
### I've made 2 main changes in this PR.

(1) The testimonials will be contracted in mobile views, concealed by a see more button.

The first three testimonials will be shown in this contracted view, with the third one fading out slightly via an image mask.

(2) Showing the third feature in mobile while in the hidden view, with the same image mask as for testimonials.

### Small Changes.

Slightly educed the opacity of the YT play button centre and added 5% of the hover opacity to video boxes by default so there's some kind of placeholder as they load in.

### Known Issues...

(1) The functionality of this kind of 'show all' list should be extracted into it's own class and passed to the mappings as a wrapper.

(2) The mobile detection functionality should be centralised.

(3) Image mask wasn't being applied when I included it in the tailwind config, so I'm using raw css for now.

### Screenshots (following changes)

IMG_5429
IMG_5428
IMG_5427

<details>
### General Contributing:

- [ ] Have you followed the guidelines in our [Contributing document](https://github.com/tinacms/tina.io/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### All New Content Submissions: (To be confirmed by reviewer)

- [ ] Title is short & specific
- [ ] Headers are logically ordered & consistent
- [ ] Purpose of document is explained in the first paragraph
- [ ] Procedures are tested and work
- [ ] Any technical concepts are explained or linked to
- [ ] Document follows structure from templates
- [ ] All links work
- [ ] The spelling and grammar checker has been run
- [ ] Graphics and images are clear and useful
- [ ] Any prerequisites and next steps are defined.
</details>

### CODE REVIEW

**Comment by isaaclombardssw** [comment]
Test passed by @landonmaxwell

**Review by joshbermanssw — CHANGES_REQUESTED** [review]
Functionality works a charm - as per our conversation if we have a 'show all' button we should have a 'hide all' button after?

**Comment by isaaclombardssw** [comment]
Done ☝️

**Review by joshbermanssw — CHANGES_REQUESTED** [review]
As per our conversation lets add an ID to the Show more buttons and when user clicks 'hide' we can use `ref.ScrollIntoView({ .... })` to smoothly return to component

**Review by joshbermanssw — APPROVED** [review]
LGTM - to make this perfect itd be cool if when i click show it was more of an accordion clean animation rather than just it appearing, and the same when i click hide. But that would be the icing

**Pull request merged**
