### PR TITLE
#1970  Fixed:1970  Side Menu

### PR DESCRIPTION
**Pull request by manideep1428**
#1970 Fixed the Side bar menu Styled on clicking them

### CODE REVIEW

**Review by isaaclombardssw — APPROVED** [review]
Looks good! 👍

Just waiting on the vercel instance to test it.

**Comment by manideep1428** [comment]
Can you say  Why vercel instance failed  , this my side or your side  PR

**Comment by joshbermanssw** [comment]
> Can you say Why vercel instance failed , this my side or your side PR

Vercel automatically fails for all users submitting PRs outside of the Tina organisation.

**Comment by isaaclombardssw** [comment]
This one is being closed as the hard coded json menu data has been refactored out.

**Pull request closed without merging**
